### ISSUE TITLE
Crash in close() function  after terminate() when logging is used

### ISSUE THREAD

**Issue by M-Startc** [pmattes/x3270#89]
I have issue when use logging  and try to use em.terinate() to finish program
My program looks like
```
em = Emulator(timeout=8000,args = ["-xrm", "-model 2", "-script"])
.....
some code
.....
em.terinate()
```
Now I have crash on em.terinate(), the tracebask is the following
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ^^^^^^^^^^^^^^^
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "/proj_path/venv/lib/python3.11/site-packages/py3270/__init__.py", line 286, in __del__
    self.terminate()
  File "/proj_path/venv/lib/python3.11/site-packages/py3270/__init__.py", line 334, in terminate
    self.app.close()
  File "/proj_path/venv/lib/python3.11/site-packages/py3270/__init__.py", line 157, in close
    log.debug("return code: %d", return_code)
Message: 'return code: %d'
Arguments: (None,)
```

I found that problen is in the following part of code of `class ExecutableApp(object)`
```
    def close(self):
        if self.sp.poll() is None:
            self.sp.terminate()
        return_code = self.sp.returncode or self.sp.poll()
        log.debug("return code: %d", return_code)
        return return_code

```
if I add `time.sleep(0.5)` after `self.sp.terminate()` like
```
    def close(self):
        if self.sp.poll() is None:
            self.sp.terminate()
            time.sleep(0.5)
        return_code = self.sp.returncode or self.sp.poll()
        log.debug("return code: %d", return_code)
        return return_code
```
then all works fine

Could you please add such delay `time.sleep(0.5)` into the `close()` function of `class ExecutableApp(object)` .

**Comment by pmattes** [comment]
Unfortunately, I am not responsible for py3270. Please re-post this to a py3270 forum.
